Fix #92, missing NonValidatingFactory in JDBC3 driver
See https://github.com/pgjdbc/pgjdbc/issues/92

You need this patch if attempts to use a URL like

    jdbc:postgresql://ipaddress:port/dbname?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory

fails with:

    java.lang.ClassNotFoundException: org.postgresql.ssl.NonValidatingFactory

in the stack trace.