bug: Compile head of postgresql with option --with-libxml
driver tests use xml feature, it tests fail with exception on head of postgresql

org.postgresql.util.PSQLException: ERROR: unsupported XML feature
  Detail: This functionality requires the server to be built with libxml support.
  Hint: You need to rebuild PostgreSQL using --with-libxml.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2453)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2153)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:286)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:432)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:358)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:305)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:291)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:269)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:249)
	at org.postgresql.test.jdbc4.jdbc41.GetObjectTest.testGetXml(GetObjectTest.java:584)