test: disable DatabaseMetaDataTest.escaping for PostgreSQL 9.1
I believe it is a known PostgreSQL 9.1 bug, which is unlikely to be fixed,
so let's ignore the test for the specific version.

The failure is as follows:
    org.postgresql.util.PSQLException: ERROR: LIKE pattern must not end with escape character
        at app//org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
        at app//org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2421)
        at app//org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:372)
        at app//org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:526)
        at app//org.postgresql.jdbc.PgStatement.execute(PgStatement.java:435)
        at app//org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
        at app//org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:139)
        at app//org.postgresql.jdbc.PgDatabaseMetaData.executeMetadataStatement(PgDatabaseMetaData.java:3163)
        at app//org.postgresql.jdbc.PgDatabaseMetaData.getTables(PgDatabaseMetaData.java:1560)
        at app//org.postgresql.test.jdbc2.DatabaseMetaDataTest.escaping(DatabaseMetaDataTest.java:1371)