bug: fix not enscaped special symbol that fail build
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (attach-javadocs) on project postgresql: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - /home/fol/project/open-source/pgjdbc/pgjdbc/target/gen-src/org/postgresql/core/Parser.java:962: warning: no @throws for java.sql.SQLException
[ERROR] public static String replaceProcessing(String p_sql, boolean replaceProcessingEnabled,
[ERROR] ^
[ERROR] /home/fol/project/open-source/pgjdbc/pgjdbc/target/gen-src/org/postgresql/jdbc/PgDatabaseMetaData.java:2138: error: bad use of '>'
[ERROR] * For instance: SELECT -> user1 -> list of [grantor, grantable]
[ERROR] ^
[ERROR] /home/fol/project/open-source/pgjdbc/pgjdbc/target/gen-src/org/postgresql/jdbc/PgDatabaseMetaData.java:2138: error: bad use of '>'
[ERROR] * For instance: SELECT -> user1 -> list of [grantor, grantable]
[ERROR] ^
[ERROR]
[ERROR] Command line was: /usr/lib/jvm/java-8-oracle/bin/javadoc -J-Xmx2048m @options
[ERROR]
[ERROR] Refer to the generated Javadoc files in '/home/fol/project/open-source/pgjdbc/pgjdbc/target/apidocs' dir.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]

```